### ISSUE TITLE
请求添加缩放功能

### ISSUE THREAD

**Issue by lanthora** [Rocket1184/electron-netease-cloud-music#16]
缩放功能(类似于 electron-wechat 的就更好了  (小声说

**Comment by rocka** [comment]
具体是怎么缩放呢？是界面显示有问题吗？还是说窗口太大屏幕放不下了？

**Comment by lanthora** [comment]
屏幕分辨率稍微高一点，字体就会很小

```css
element.style {
    zoom: 1.25;
}
```

在开发者模式加了这个标签，看起来舒服一些了。
希望可以有个设置缩放的选项，这样不同分辨率的屏幕可以自己调
